const { v4: uuidv4 } = require("uuid");

const transactions = [
  {
    id: uuidv4(),
    item_name: "Paycheck",
    amount: 2500,
    date: "April 1",
    from: "New York Unified Court System",
    category: "Income",
  },
  {
    id: uuidv4(),
    item_name: "Taxes",
    amount: -300,
    date: "April 1",
    from: "NYS",
    category: "Taxes",
  },
  {
    id: uuidv4(),
    item_name: "Retirement",
    amount: -200,
    date: "April 1",
    from: "Deferred Compensation",
    category: "Retirement",
  },
  {
    id: uuidv4(),
    item_name: "Savings",
    amount: -100,
    date: "April 1",
    from: "Me",
    category: "Savings",
  },
  {
    id: uuidv4(),
    item_name: "Credit Card Payment",
    amount: -100,
    date: "April 2",
    from: "MasterCard",
    category: "Consumer Debt",
  },
  {
    id: uuidv4(),
    item_name: "Birthday Money",
    amount: 20,
    date: "April 5",
    from: "Auntie Zell",
    category: "Gift",
  },
  {
    id: uuidv4(),
    item_name: "Coffee",
    amount: -4,
    date: "April 5",
    from: "Starbucks",
    category: "Food",
  },
  {
    id: uuidv4(),
    item_name: "Internet",
    amount: -100,
    date: "April 5",
    from: "Optimum",
    category: "Utility",
  },
  {
    id: uuidv4(),
    item_name: "Groceries",
    amount: -76,
    date: "April 11",
    from: "BJ's",
    category: "Food",
  },
  {
    id: uuidv4(),
    item_name: "Pet Food",
    amount: -7,
    date: "April 11",
    from: "Stop N Shop",
    category: "Pet Food",
  },
  {
    id: uuidv4(),
    item_name: "Hair Salon",
    amount: -260,
    date: "April 13",
    from: "Glow Hair and Nails",
    category: "Personal",
  },
  {
    id: uuidv4(),
    item_name: "Rent",
    amount: -1280,
    date: "April 7",
    from: "Cornell Pace Management",
    category: "Housing",
  },
  {
    id: uuidv4(),
    item_name: "Insurance",
    amount: -280,
    date: "April 13",
    from: "Liberty Mutual",
    category: "Auto Insurance",
  },
];

module.exports = transactions;
